add check order method
nikita-vanyasin/tinkoff pull request #13
Opened 2024-11-16 09:55 UTC by AlexTransit

добавлен метод проверки заказа
[https://www.tbank.ru/kassa/dev/payments/#tag/Standartnyj-platezh/operation/CheckOrder](url)

думал  что покажет все операции по заказу, а по факту показывает только последнюю.

был прецедент.
сделал сгенерил QR. 
клиент оплатил его. 
в процессе выполнения у робота произошла ошибка.
сервер сделал отмену платежа. все прошло без ошибок.
а потом банк отменил возврат и уведомление не прислал. :) 

со слов поддержки, типа не было средств на счету. по идее это можно эмулировать. 
или в конце дня проверять соответствие статусов на отмененные заказы.

2024-11-18 09:33 UTC, nikita-vanyasin commented on checkorder.go
> +	Payments []struct {
Все отлично, но давай вытащим объявление структуры в отдельный тип

2024-11-18 13:52 UTC, AlexTransit commented on checkorder.go
> +	Payments []struct {
поправил.

2024-11-18 20:58 UTC, nikita-vanyasin requested changes

2024-11-18 20:58 UTC, nikita-vanyasin commented on checkorder.go
> +type Payment struct {
Payment очень общее, может конфликтовать с другими методами. В доке это называется PaymentsCheckOrder - как-то не очень ложится на Go-стиль. Думаю CheckOrderPayment подойдет

2024-11-18 20:58 UTC, nikita-vanyasin commented on checkorder.go
> +	Amount       uint64 `json:"Amount"`            // Стоимость товара в копейках
```suggestion
	Amount       uint64 `json:"Amount,omitempty"`            // Стоимость товара в копейках
```

2024-11-18 20:58 UTC, nikita-vanyasin commented on checkorder.go
> +	RRN          string `json:"RRN"`               // Внутренний номер операции в платежной системе — кроме операций по СБП.
```suggestion
	RRN          string `json:"RRN,omitempty"`               // Внутренний номер операции в платежной системе — кроме операций по СБП.
```

2024-11-18 20:58 UTC, nikita-vanyasin commented on checkorder.go
> +	ErrorCode    string `json:"ErrorCode"`         // Код ошибки, «0» - если успешно
Вот тут точно строка а не int? в доке написано number. А в примере ответа - "0".
Предлагаю добавить проверку этого метода в тест: https://github.com/nikita-vanyasin/tinkoff/blob/master/compound_test.go#L1
Можно обновить тестовый сценарий чтобы у заказа появились платежи, а потом сделать CheckOrder и проверить что ErrorCode парсится без ошибок.

2024-11-19 08:19 UTC, AlexTransit commented
приношу извинения, что создал чтолько проблем. :) 
просто я не програмирую. приходиться исправлять/добавлять наследие. :)
исправил все что Вы указали.

2024-11-22 02:20 UTC, AlexTransit commented on checkorder.go
> +	ErrorCode    uint64 `json:"ErrorCode"`         // Код ошибки, «0» - если успешно
Ok. я проверю что они возвращают в ErrorCode.

2024-12-01 11:56 UTC, AlexTransit commented on checkorder.go
> +	ErrorCode    uint64 `json:"ErrorCode"`         // Код ошибки, «0» - если успешно
извините за задержку.
у меня не получилось проверить. я не знаю как сделать заказ с ошибкой в платеже.  
возможно что никак. 
думаю что надо оставить код ошибки в списке PaymentsCheckOrder как в описании.  
ErrorCode | number
и в примере тоже "ErrorCode": 0

а вот ошибка код ошибки в корневом ответе - стока. и проверить легко. поставил несуществующий заказ и получил код ошибки с типом string.

2024-12-09 20:58 UTC, merged