Реализация метода Charge для рекурентных платежей
nikita-vanyasin/tinkoff pull request #15
Opened 2024-12-16 15:24 UTC by mazhigali

Привет согласно документации сделал https://www.tbank.ru/kassa/dev/payments/#tag/Rekurrentnyj-platezh/operation/ChargePCI. На своем проекте проверил, работает.

2024-12-21 17:55 UTC, nikita-vanyasin requested changes
Спасибо! Есть несколько комментов 👌🏻

2024-12-21 17:55 UTC, nikita-vanyasin commented on charge.go
> +	PaymentId string `json:"PaymentId,omitempty"` // Уникальный идентификатор транзакции в системе Т‑Кассы
```suggestion
	PaymentID string `json:"PaymentId,omitempty"` // Уникальный идентификатор транзакции в системе Т‑Кассы
```

2024-12-21 17:55 UTC, nikita-vanyasin commented on charge.go
> +	RebillId  string `json:"RebillId,omitempty"`  // Идентификатор рекуррентного платежа
```suggestion
	RebillID  string `json:"RebillId,omitempty"`  // Идентификатор рекуррентного платежа
```

2024-12-21 17:55 UTC, nikita-vanyasin commented on charge.go
> +		"PaymentId": i.PaymentId,
```suggestion
		"PaymentId": i.PaymentID,
```

2024-12-21 17:55 UTC, nikita-vanyasin commented on charge.go
> +		"RebillId":  i.RebillId,
```suggestion
		"RebillId":  i.RebillID,
```

2024-12-21 17:55 UTC, nikita-vanyasin commented on notification.go
> +	RebillID       uint64            `json:"RebillId"`    // Идентификатор рекуррентного платежа
Вот это изменения не могу принять - breaking change
Если эта колонка должна быть uint64 то нужно сделать новое поле и заполнять оба поля при парсинге

2025-02-23 06:11 UTC, mazhigali commented on notification.go
> +	RebillID       uint64            `json:"RebillId"`    // Идентификатор рекуррентного платежа
Я думаю не обязательно чтобы RebillID был uint64, но  входящий JSON содержит поле RebillId как число (3207469334) (пример json в документации https://www.tbank.ru/kassa/dev/payments/#tag/Uvedomleniya-ob-operaciyah/operation/Notification) , а если в структуре Go это поле объявлено как string, то json.Unmarshal вернёт ошибку json: cannot unmarshal number into Go struct field Notification.RebillId of type string.

2025-03-02 09:30 UTC, nikita-vanyasin commented on notification.go
> +	RebillID       uint64            `json:"RebillId"`    // Идентификатор рекуррентного платежа
Полностью согласен - если поле приходит числовое по факту, то нужно парсить как число.

Но смена типа у существующего поля это breaking change.
Нужно сделать новое поле (uint64). И сохранить старое:
```
// Deprecated, use RebillIDUint64
RebillID          string        `json:"-"`
RebillIDUInt64    uint64        `json:"RebillId"`
```

и потом 
```
result.RebillID = strconv.FormatUint(result.RebillIDUInt64, 10)
```

2025-03-05 20:26 UTC, dilap54 reviewed
Это древний PR, но мне он внезапно оказался нужен, поэтому поучаствую

2025-03-05 20:26 UTC, dilap54 commented on notification.go
> +	RebillID       uint64            `json:"RebillId"`    // Идентификатор рекуррентного платежа
Это не breaking change, потому что это поле, похоже, никогда не работало. Вот точный json, который тинёк присылает в http уведомлениях:
```json
{
  "TerminalKey": "1726675329428DEMO",
  "OrderId": "9863471b-8d42-4617-9073-11339159aba9",
  "Success": true,
  "Status": "AUTHORIZED",
  "PaymentId": 5974256058,
  "ErrorCode": "0",
  "Amount": 19900,
  "CardId": 475738102,
  "Pan": "430000******0777",
  "ExpDate": "1230",
  "RebillId": 1741204285536,
  "Token": "31e30b09fc1394cb6484c695eb62b69d324e7b766ad0a20726753f61162e11fb"
}
```
И вот что получаешь, если пытаешься его распарсить:
```
json: cannot unmarshal number into Go struct field Notification.RebillId of type string
```

2025-03-05 20:50 UTC, nikita-vanyasin commented
@dilap54 

> поле, похоже, никогда не работало.

понимаю.

Но с точки зрения этого пакета (https://github.com/nikita-vanyasin/tinkoff) смена типа у поля - breaking change. 

Представь например ситуацию, где кто-то уже написал код который подразумевает, что RebillID - строка. Если поменять тип - этот код перестанет работать. Даже если по факту там всегда было неправильно / не парсилось - код перестанет собираться если просто поменять тип.

Добавление нового поля безусловано не самая хорошая вещь, но это лучше чем потенциальные проблемы с совместимостью. 

Я добавлю это поле сам на следующей неделе, если никто не сделает раньше ^

2025-03-05 21:36 UTC, dilap54 commented
@nikita-vanyasin Понял аргумент про breaking change. Переоткрыл этот же PR с правками по твоим замечаниям https://github.com/nikita-vanyasin/tinkoff/pull/17

2025-03-06 20:52 UTC, nikita-vanyasin commented
Спасибо! Оформлю новый тег ддя релиза 👍🏻

2025-03-06 20:52 UTC, closed without merging